version: "3.7"
services:
  rabbit:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
  marie:
    build: ./MarieService
    ports:
      - "82:8082"
    depends_on:
      - rabbit
